In [22]:
# Import data

import pandas as pd
shark_attacks = pd.read_excel('https://www.sharkattackfile.net/spreadsheets/GSAF5.xls')

In [23]:
shark_attacks.drop_duplicates(inplace=True)

In [25]:
# Filter for data containing “Australia”  from “Country” (Florian)
shark_attacks_australia = shark_attacks[shark_attacks['Country'].str.contains("Australia", case=False, na=False)]

In [34]:
import pandas as pd

# Assuming shark_attacks_australia is your DataFrame

# Define a custom date parser
def custom_date_parser(date_str):
    try:
        return pd.to_datetime(date_str, format='%d %b-%Y')
    except ValueError:
        return pd.to_datetime(date_str, errors='coerce')

# Apply the custom date parser to the "Date" column in the DataFrame
shark_attacks_australia['Date'] = shark_attacks_australia['Date'].apply(custom_date_parser)

# Extract the month from the "Date" column using .loc to avoid SettingWithCopyWarning
shark_attacks_australia.loc[:, 'Month'] = shark_attacks_australia['Date'].dt.month

# Display the DataFrame with the extracted month
print(shark_attacks_australia[['Date', 'Month']])

           Date  Month
0    2024-01-09    1.0
4    2023-12-28   12.0
5    2023-12-25   12.0
6    2023-12-24   12.0
10   2023-12-08   12.0
...         ...    ...
6707 1832-06-04    6.0
6746 1807-01-12    1.0
6751 1803-03-01    3.0
6757 1791-01-01    1.0
6758 1788-05-10    5.0

[1312 rows x 2 columns]

In [35]:
# Remove Null Values from "Month"
shark_attacks_australia = shark_attacks_australia.dropna(subset=['Month'])
shark_attacks_australia

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Month,fatal_or_not
0,2024-01-09,2024.0,Unprovoked,AUSTRALIA,South Australia,"Walkers Beach, Elliston",Surfing,Murray Adams,M,64,...,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,1.0,0
4,2023-12-28,2023.0,Unprovoked,AUSTRALIA,South Australia,Ethel Beach,Surfing,Khai Cowley,M,15,...,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,12.0,1
5,2023-12-25,2023.0,Unprovoked,AUSTRALIA,New South Wales,Old Bar,Surfing,Julian McLennan,M,16,...,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,12.0,0
6,2023-12-24,2023.0,Unprovoked,AUSTRALIA,Western Australia,Wedge Island,Foil Boarding,Troy Brown,M,46,...,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,12.0,0
10,2023-12-08,2023.0,Unprovoked,AUSTRALIA,Queensland,1770,Snorkeling,Matteo Mariotti,M,20,...,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,New South Wales,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6707,1832-06-04,1832.0,Unprovoked,AUSTRALIA,New South Wales,"South Head, Sydney",Fishing,Aboriginal female,F,New South Wales,...,1832.06.04-AboriginalWoman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1832.06.04,1832.06.04,224.0,New South Wales,New South Wales,6.0,0
6746,1807-01-12,1807.0,Unprovoked,AUSTRALIA,New South Wales,"Cockle Bay, Sydney Harbour",New South Wales,male,M,New South Wales,...,1807.01.12-Cockle-Bay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1807.01.12,1807.01.12,185.0,New South Wales,New South Wales,1.0,0
6751,1803-03-01,1803.0,Unprovoked,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",New South Wales,M. Lefevre & a sailor (rescuer),M,New South Wales,...,1803.03.00-Lefevre.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.03.00,1803.03.00,180.0,New South Wales,New South Wales,3.0,0
6757,1791-01-01,1791.0,Unprovoked,AUSTRALIA,New South Wales,Port Jackson,New South Wales,"female, an Australian aboriginal",F,New South Wales,...,1791.00.00-aboriginal woman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1791.00.00,1791.00.00,174.0,New South Wales,New South Wales,1.0,1
6758,1788-05-10,1788.0,Watercraft,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,boat,New South Wales,New South Wales,...,1788.05.10-Sydney,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1788.05.10,1788.05.10,173.0,New South Wales,New South Wales,5.0,0

In [36]:
#State (Hanieh)
shark_attacks_australia.isnull().sum()
shark_attacks_australia["State"].mode()[0]
shark_attacks_australia = shark_attacks_australia.fillna(shark_attacks_australia["State"].mode()[0])
shark_attacks_australia["State"].isnull().sum()

0

In [37]:
#Injury (Erensu)
import re
def fatal_or_not(Injury):
    case = str(Injury).strip()
    if re.search(r'fatal', case, flags=re.IGNORECASE):
        return 1
    else:
        return 0
fatal_or_not_list=[]
for i in shark_attacks_australia.Injury:
    a=fatal_or_not(i)
    fatal_or_not_list.append(a)

shark_attacks_australia['fatal_or_not']=fatal_or_not_list

In [38]:
# pip install pandas
!pip install pandas

Requirement already satisfied: pandas in /Users/bart/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /Users/bart/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [39]:
# Export as an excel file

shark_attacks_australia.to_csv("Shark_Attack_CSV_V4.csv", index=False)

In [40]:
shark_attacks_australia.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1312 entries, 0 to 6758
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1312 non-null   datetime64[ns]
 1   Year            1312 non-null   float64
 2   Type            1312 non-null   object
 3   Country         1312 non-null   object
 4   State           1312 non-null   object
 5   Location        1312 non-null   object
 6   Activity        1312 non-null   object
 7   Name            1312 non-null   object
 8   Sex             1312 non-null   object
 9   Age             1312 non-null   object
 10  Injury          1312 non-null   object
 11  Unnamed: 11     1312 non-null   object
 12  Time            1312 non-null   object
 13  Species         1312 non-null   object
 14  Source          1312 non-null   object
 15  pdf             1312 non-null   object
 16  href formula    1312 non-null   object
 17  href            1312 non-null   object
 18  Case Number     1312 non-null   object
 19  Case Number.1   1312 non-null   object
 20  original order  1312 non-null   object
 21  Unnamed: 21     1312 non-null   object
 22  Unnamed: 22     1312 non-null   object
 23  Month           1312 non-null   float64
 24  fatal_or_not    1312 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 266.5+ KB