In [11]:
# Import data

import pandas as pd
shark_attacks = pd.read_excel('https://www.sharkattackfile.net/spreadsheets/GSAF5.xls')

In [12]:
shark_attacks.drop_duplicates(inplace=True)

In [13]:
# Filter for data containing “Australia”  from “Country” (Florian)
shark_attacks_australia = shark_attacks[shark_attacks['Country'].str.contains("Australia", case=False, na=False)]
print(shark_attacks_australia)

             Date    Year        Type    Country              State  \
0     09-Jan-2024  2024.0  Unprovoked  AUSTRALIA    South Australia
4     28 Dec-2023  2023.0  Unprovoked  AUSTRALIA    South Australia
5     25 Dec-2023  2023.0  Unprovoked  AUSTRALIA    New South Wales
6     24-Dec-2023  2023.0  Unprovoked  AUSTRALIA  Western Australia
10    08 Dec-2023  2023.0  Unprovoked  AUSTRALIA         Queensland
...           ...     ...         ...        ...                ...
6924  Before 1906     0.0  Unprovoked  AUSTRALIA                NaN
6925  Before 1906     0.0  Unprovoked  AUSTRALIA                NaN
6926  Before 1906     0.0  Unprovoked  AUSTRALIA    New South Wales
6927  Before 1903     0.0  Unprovoked  AUSTRALIA  Western Australia
6928  Before 1903     0.0  Unprovoked  AUSTRALIA  Western Australia

                     Location       Activity             Name Sex  Age  ...  \
0     Walkers Beach, Elliston        Surfing     Murray Adams   M   64  ...
4                 Ethel Beach        Surfing      Khai Cowley   M   15  ...
5                     Old Bar        Surfing  Julian McLennan   M   16  ...
6                Wedge Island  Foil Boarding       Troy Brown   M   46  ...
10                      1770      Snorkeling  Matteo Mariotti   M   20  ...
...                       ...            ...              ...  ..  ...  ...
6924                      NaN        Fishing        fisherman   M  NaN  ...
6925                      NaN        Fishing        fisherman   M  NaN  ...
6926                                Swimming         Arab boy   M  NaN  ...
6927              Roebuck Bay         Diving             male   M  NaN  ...
6928                      NaN   Pearl diving            Ahmun   M  NaN  ...

                                               Species   \
0                                           White shark
4                                      White shark, 13'
5                                                   NaN
6                                         Broze whaler?
10                                                  NaN
...                                                 ...
6924                                       Blue pointer
6925                                      Blue pointers
6926  Said to involve a grey nurse shark that leapt ...
6927                                                NaN
6928                                                NaN

                                                 Source  \
0                                       A. Currie, GSAF
4                                     S. DeMarchi, GSAF
5                                    9 News, 12/26/2023
6                                    9 News, 12/25/2023
10                                       B. Myatt, GSAF
...                                                 ...
6924  NY Sun, 9/9/1906, referring to account by Loui...
6925  NY Sun, 9/9/1906, referring to account by Loui...
6926  L. Becke in New York Sun, 9/9/1906; L. Schultz...
6927                   H. Taunton; N. Bartlett,  p. 234
6928              H. Taunton; N. Bartlett,  pp. 233-234

                                    pdf  \
0                                   NaN
4                                   NaN
5                                   NaN
6                                   NaN
10                                  NaN
...                                 ...
6924   ND-0008-Fisherman2-Australia.pdf
6925  ND-0007 - Fisherman-Australia.pdf
6926       ND-0006-ArabBoy-Prymount.pdf
6927             ND-0005-RoebuckBay.pdf
6928                  ND-0004-Ahmun.pdf

                                           href formula  \
0                                                   NaN
4                                                   NaN
5                                                   NaN
6                                                   NaN
10                                                  NaN
...                                                 ...
6924  http://sharkattackfile.net/spreadsheets/pdf_di...
6925  http://sharkattackfile.net/spreadsheets/pdf_di...
6926  http://sharkattackfile.net/spreadsheets/pdf_di...
6927  http://sharkattackfile.net/spreadsheets/pdf_di...
6928  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number  \
0                                                   NaN         NaN
4                                                   NaN         NaN
5                                                   NaN         NaN
6                                                   NaN         NaN
10                                                  NaN         NaN
...                                                 ...         ...
6924  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0008
6925  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0007
6926  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0006
6927  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0005
6928  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0004

     Case Number.1 original order Unnamed: 21 Unnamed: 22
0              NaN            NaN         NaN         NaN
4              NaN            NaN         NaN         NaN
5              NaN            NaN         NaN         NaN
6              NaN            NaN         NaN         NaN
10             NaN            NaN         NaN         NaN
...            ...            ...         ...         ...
6924       ND.0008            9.0         NaN         NaN
6925       ND.0007            8.0         NaN         NaN
6926       ND.0006            7.0         NaN         NaN
6927       ND.0005            6.0         NaN         NaN
6928       ND.0004            5.0         NaN         NaN

[1478 rows x 23 columns]

In [14]:
# Extract “Month” from “Date” (Bartek)

def custom_date_parser(date_str):
    try:
        return pd.to_datetime(date_str, format='%d %b-%Y')
    except ValueError:
        return pd.to_datetime(date_str, errors='coerce')
# Apply the custom date parser to the "Date" column in the shark_attacks_australia DataFrame
shark_attacks_australia['Date'] = shark_attacks_australia['Date'].apply(custom_date_parser)
# Extract the month from the "Date" column
shark_attacks_australia['Month'] = shark_attacks_australia['Date'].dt.month
# Display the DataFrame with the extracted month
print(shark_attacks_australia[['Date', 'Month']])

           Date  Month
0    2024-01-09    1.0
4    2023-12-28   12.0
5    2023-12-25   12.0
6    2023-12-24   12.0
10   2023-12-08   12.0
...         ...    ...
6924        NaT    NaN
6925        NaT    NaN
6926        NaT    NaN
6927        NaT    NaN
6928        NaT    NaN

[1478 rows x 2 columns]

/var/folders/sf/38y5z2k91sx3rlh15tb__lyw0000gn/T/ipykernel_60574/2656191740.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attacks_australia['Date'] = shark_attacks_australia['Date'].apply(custom_date_parser)
/var/folders/sf/38y5z2k91sx3rlh15tb__lyw0000gn/T/ipykernel_60574/2656191740.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_attacks_australia['Month'] = shark_attacks_australia['Date'].dt.month

In [15]:
# Remove Null Values from "Month"
shark_attacks_australia = shark_attacks_australia.dropna(subset=['Month'])

shark_attacks_australia

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Month
0,2024-01-09,2024.0,Unprovoked,AUSTRALIA,South Australia,"Walkers Beach, Elliston",Surfing,Murray Adams,M,64,...,"A. Currie, GSAF",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,2023-12-28,2023.0,Unprovoked,AUSTRALIA,South Australia,Ethel Beach,Surfing,Khai Cowley,M,15,...,"S. DeMarchi, GSAF",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
5,2023-12-25,2023.0,Unprovoked,AUSTRALIA,New South Wales,Old Bar,Surfing,Julian McLennan,M,16,...,"9 News, 12/26/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
6,2023-12-24,2023.0,Unprovoked,AUSTRALIA,Western Australia,Wedge Island,Foil Boarding,Troy Brown,M,46,...,"9 News, 12/25/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
10,2023-12-08,2023.0,Unprovoked,AUSTRALIA,Queensland,1770,Snorkeling,Matteo Mariotti,M,20,...,"B. Myatt, GSAF",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6707,1832-06-04,1832.0,Unprovoked,AUSTRALIA,New South Wales,"South Head, Sydney",Fishing,Aboriginal female,F,NaN,...,"Sydney Herald, 6/11/1832",1832.06.04-AboriginalWoman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1832.06.04,1832.06.04,224.0,NaN,NaN,6.0
6746,1807-01-12,1807.0,Unprovoked,AUSTRALIA,New South Wales,"Cockle Bay, Sydney Harbour",NaN,male,M,NaN,...,"J. Green, p.31",1807.01.12-Cockle-Bay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1807.01.12,1807.01.12,185.0,NaN,NaN,1.0
6751,1803-03-01,1803.0,Unprovoked,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,M. Lefevre & a sailor (rescuer),M,NaN,...,F. Peron ref in G.P. Whitley (Fishes of Austr...,1803.03.00-Lefevre.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.03.00,1803.03.00,180.0,NaN,NaN,3.0
6757,1791-01-01,1791.0,Unprovoked,AUSTRALIA,New South Wales,Port Jackson,NaN,"female, an Australian aboriginal",F,NaN,...,"G.P. Whitley; D. Baldridge, p.162",1791.00.00-aboriginal woman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1791.00.00,1791.00.00,174.0,NaN,NaN,1.0
6758,1788-05-10,1788.0,Watercraft,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,boat,NaN,NaN,...,"G.P. Whitley citing J. Cobley, Sydney Cove, p....",1788.05.10-Sydney,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1788.05.10,1788.05.10,173.0,NaN,NaN,5.0

In [16]:
#State (Hanieh)
shark_attacks_australia.isnull().sum()
shark_attacks_australia["State"].mode()[0]
shark_attacks_australia = shark_attacks_australia.fillna(shark_attacks_australia["State"].mode()[0])
shark_attacks_australia["State"].isnull().sum()

0

In [17]:
#Injury (Erensu)
import re
def fatal_or_not(Injury):
    case = str(Injury).strip()
    if re.search(r'fatal', case, flags=re.IGNORECASE):
        return 1
    else:
        return 0
fatal_or_not_list=[]
for i in shark_attacks_australia.Injury:
    a=fatal_or_not(i)
    fatal_or_not_list.append(a)

shark_attacks_australia['fatal_or_not']=fatal_or_not_list

In [18]:
# pip install pandas
!pip install pandas

Requirement already satisfied: pandas in /Users/bart/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/bart/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /Users/bart/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [20]:
# Export as an excel file

shark_attacks_australia.to_csv("Shark_Attack_CSV.csv", index=False)

In [10]:
shark_attacks_australia.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1312 entries, 0 to 6758
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1312 non-null   datetime64[ns]
 1   Year            1312 non-null   float64
 2   Type            1312 non-null   object
 3   Country         1312 non-null   object
 4   State           1312 non-null   object
 5   Location        1312 non-null   object
 6   Activity        1312 non-null   object
 7   Name            1312 non-null   object
 8   Sex             1312 non-null   object
 9   Age             1312 non-null   object
 10  Injury          1312 non-null   object
 11  Unnamed: 11     1312 non-null   object
 12  Time            1312 non-null   object
 13  Species         1312 non-null   object
 14  Source          1312 non-null   object
 15  pdf             1312 non-null   object
 16  href formula    1312 non-null   object
 17  href            1312 non-null   object
 18  Case Number     1312 non-null   object
 19  Case Number.1   1312 non-null   object
 20  original order  1312 non-null   object
 21  Unnamed: 21     1312 non-null   object
 22  Unnamed: 22     1312 non-null   object
 23  Month           1312 non-null   float64
 24  fatal_or_not    1312 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 266.5+ KB